# Site settings
title:    Doctor Professor
email:
description: > # this means to ignore newlines until "baseurl:"
  Professor of Subject at University of State and author of *Famous Book*
baseurl: "/sample2"
url: "http://www.keithbuhler.com" # the base hostname & protocol for your site

# User setting
owner:
email:
facebook_username:
twitter_username:
github_username:
address:
  - line:
  - line:
  # Feel free to add more lines here 
telephone:
copyright:

# API settings
google_api_key:

# Build settings
markdown: kramdown
